### ISSUE TITLE
Teleport to player or waypoint is not detected as power cast.

### ISSUE THREAD

**Issue by Enigma32** [Enigma32/D3Helper.Public#2]
Teleport to player or waypoint is not detected as power cast as mentioned here https://github.com/Enigma32/D3Helper.Public/pull/1#issuecomment-239679921.

**Comment by ne0ark** [comment]
It seems like https://github.com/Enigma32/D3Helper.Public/commit/1e9fed1898baebf19dc7057441b6c6a97dd94064 broke things more.

**Comment by d2k2-git** [comment]
@ne0ark can you explain what exactly is broken more and what this fix has to do with the teleport detection?

**Comment by ne0ark** [comment]
Before that commit. You can teleport even when you had cast on cooldown for a skill. Now the teleport to a player gets interrupted by the spell. It should pause the skill rules when using teleport. Before that commit, it temporarily stops the rules when teleport is used until you cast a skill manually. I hope that makes it little more clear.

**Comment by d2k2-git** [comment]
@ne0ark it "worked" probably before because d3helper get stuck into that infinite loop and then stopped working.

btw, this topic is discussing another issue
