### ISSUE TITLE
Condition Key Force Standstill.

### ISSUE THREAD

**Issue by ne0ark** [Enigma32/D3Helper.Public#4]
Reported here: http://d3helper.freeforums.net/post/1889

It seems like Key Force Standstill (Selected) and Select Monster distance (10). It does not cast the skill. However, if Key Force Standstill (Unselected) which is equivalent to force move works in similar condition.

**Comment by ne0ark** [comment]
It seems like http://d3helper.freeforums.net/post/1887 version is working properly with standstill. The version that I compiled has many problems.

**Comment by d2k2-git** [comment]
@ne0ark thats why i wrote be sure you are using the release with latest commits from enigmas repository. otherwise it could be you will report bugs which has been already fixed or dont exist.

**Comment by ne0ark** [comment]
Will close the issue since this is related to issue #3 .
